#!/bin/sh

gcc -I./lib -O3 -DDEBUG_MODE -std=c11 -fPIC -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -pthread -mavx -mf16c -msse3 -msse -c lib/ggml.c -o lib/ggml.o
#g++ -I./lib -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -pthread -mavx -mf16c -msse3 -msse -c lib/encoder_utils.cpp -o lib/encoder_utils.o
g++ -I./lib -O3 -DDEBUG_MODE -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -pthread -mavx -mf16c -msse3 -msse -c lib/encoder.cpp -o lib/encoder.o
g++ -I./lib -o3 -DDEBUG_MODE -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -pthread -mavx -mf16c -msse3 -msse -c lib/copy_results.cpp -o lib/copy_results.o                      
g++ -I./lib -DDEBUG_MODE -Wfatal-errors lib/common/common.cpp main.cpp lib/ggml.o lib/copy_results.o lib/encoder.o -o encoder_cli